CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    isOwner BOOLEAN,
    restaurantOwned INT NOT NULL
);

CREATE TABLE Restaurants (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    floor INT,
    MobileOrder BOOLEAN,
    OpeningTime TIME,
    ClosingTime TIME,
    ownedBY INT NOT NULL REFERENCES Users(id)
);

CREATE TABLE Recommendations (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    time_submitted timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    popularity INT NOT NULL
);

CREATE TABLE RecPhotos (
    rec_id INT NOT NULL REFERENCES Recommendations(id),
    filename VARCHAR(100) NOT NULL,
    PRIMARY KEY(rec_id, filename)
);

CREATE TABLE RecTags (
    rec_id INT NOT NULL REFERENCES Recommendations(id),
    tag_name VARCHAR(100) NOT NULL
);


CREATE TABLE fooditems (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    price FLOAT NOT NULL,
    protein FLOAT NOT NULL,
    sugars FLOAT NOT NULL,
    fats FLOAT NOT NULL,
    calories INT NOT NULL,
    allergens VARCHAR(50) NOT NULL,
    restaurantID INT NOT NULL REFERENCES Restaurants(id),
    diet VARCHAR(100)
);

CREATE TABLE RecFoods (
    rec_id INT NOT NULL REFERENCES Recommendations(id),
    food_id INT NOT NULL REFERENCES fooditems(id)
);

CREATE TABLE Reviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    rating INT NOT NULL,
    description VARCHAR(300) NOT NULL,
    restaurant_id INT NOT NULL REFERENCES Restaurants(id),
    anonymous BOOLEAN NOT NULL
);

CREATE VIEW MostAttachedFood AS
SELECT fooditems.name, Restaurants.name as rName, COUNT(*) as freq
FROM RecFoods, fooditems, Restaurants
WHERE fooditems.id = food_id AND Restaurants.id = fooditems.restaurantID
GROUP BY fooditems.id, fooditems.name, Restaurants.name
ORDER BY freq DESC
LIMIT 10;

CREATE VIEW MostPopularFood AS
SELECT fooditems.name, Restaurants.name as rName, SUM(popularity) as total_pop
FROM RecFoods, fooditems, Restaurants, Recommendations
WHERE fooditems.id = food_id AND Restaurants.id = fooditems.restaurantID and rec_id = Recommendations.id
GROUP BY fooditems.id, fooditems.name, Restaurants.name
ORDER BY total_pop DESC
LIMIT 10;